sudo: required

services:
  - docker

before_install:
  - docker build -t atultambe14/docker-react -f Dockerfile.dev .

script:
  - docker run atultambe14/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region:  "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-556445521692"
  bucket_path: "docker-react"
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
